version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    image: nginx:alpine
    ports:
      - 8085:80
    networks:
      - internal
    volumes:
      - .:/var/www/html/
      - ./logs/nginx:/var/log/nginx/
    depends_on:
      - php      
  
  php:
    image: php:8.1-fpm-alpine
    user: root
    build:
      context: .
      dockerfile: php.Dockerfile
    networks:
      - internal
    volumes:
      - .:/var/www/html/
    depends_on:
      - mysql
  
  mysql:
    image: mysql:5.7.22 
    restart: always 
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123 
      MYSQL_DATABASE: mlite_db 
    ports:
      - 3308:3306
    expose:
      - 3308
    volumes:
      - ./mysql:/var/lib/mysql  
      - ./db:/docker-entrypoint-initdb.d

networks:
  internal:
    driver: bridge